version: "3.3"
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:8000"
      - "443:8443"
    volumes:
      - ./socks-gui:/var/www/socks-gui
      - ./prod/nginx:/etc/nginx/conf.d
      - ./prod/logs:/var/logs/nginx
    depends_on:
      - django
  django:
    build: .
    restart: always
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate"
    volumes:
      - ./socks:/var/www/socks
    expose:
     - "8000"
     - "8443"
    depends_on:
     - db
  db:
    restart: always
    image: postgres:10.3
    volumes:
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./database-backup:/database-backup
volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
