# Generated by Django 3.1.1 on 2020-12-18 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201216_0352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.RemoveField(
            model_name='event',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starttime',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='role',
            field=models.CharField(default='Other', max_length=30),
        ),
    ]
