# Generated by Django 3.1.1 on 2020-12-18 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201218_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Shiftevent',
        ),
        migrations.CreateModel(
            name='Oooevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=30)),
                ('reason', models.CharField(max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
        ),
    ]
