# Generated by Django 3.1.1 on 2020-12-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201218_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftevent',
            old_name='name',
            new_name='employee',
        ),
    ]
