# Generated by Django 3.1.1 on 2020-12-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201218_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shiftevent',
            old_name='employee',
            new_name='name',
        ),
    ]
